name: controle_financeiro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  custom_sliding_segmented_control: ^1.8.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  table_calendar: ^3.1.1
  cloud_firestore: ^5.0.0
  uuid: ^4.4.0
  provider: ^6.1.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/icone.png"
  min_sdk_android: 21

flutter:
  assets: 
    - assets/image/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Icone.png"
  